language: node_js

node_js: 
  - "14"

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: ./packages/docs/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - npm install -g yarn

cache:
  npm: true
  yarn: true

install:
  - yarn

script:
  - npm run build

after_success:
  - cd ./packages/docs/dist
